### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by convosasha** [borisdayma/semantic-segmentation#1]
Hello,
I tried to run the code in pycharm, but at the very beginning, while doing wandb.init(), i receive an error message:
`wandb: Tracking run with wandb version 0.8.29
Traceback (most recent call last):
  File "C:\Users\kserc\Anaconda3\lib\site-packages\wandb\internal_cli.py", line 106, in <module>
    main()
  File "C:\Users\kserc\Anaconda3\lib\site-packages\wandb\internal_cli.py", line 98, in main
    headless(args)
  File "C:\Users\kserc\Anaconda3\lib\site-packages\wandb\internal_cli.py", line 54, in headless
    util.sentry_reraise(e)
  File "C:\Users\kserc\Anaconda3\lib\site-packages\wandb\util.py", line 94, in sentry_reraise
    six.reraise(type(exc), exc, sys.exc_info()[2])
  File "C:\Users\kserc\Anaconda3\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Users\kserc\Anaconda3\lib\site-packages\wandb\internal_cli.py", line 52, in headless
    user_process_pid, stdout_master_fd, stderr_master_fd)
  File "C:\Users\kserc\Anaconda3\lib\site-packages\wandb\run_manager.py", line 1137, in wrap_existing_process
    stderr_read_file = os.fdopen(stderr_read_fd, 'rb')
  File "C:\Users\kserc\Anaconda3\lib\os.py", line 1027, in fdopen
    return io.open(fd, *args, **kwargs)
OSError: [WinError 6] The handle is invalid
wandb: ERROR W&B process (PID 20204) did not respond
wandb: ERROR W&B process failed to launch, see: wandb\debug.log
Traceback (most recent call last):
  File "D:/work/wisense/home_assignment_2/my_setup/fastai_resnet18/src/train.py", line 12, in <module>
    wandb.init()
  File "C:\Users\kserc\Anaconda3\lib\site-packages\wandb\__init__.py", line 1088, in init
    _init_headless(run)
  File "C:\Users\kserc\Anaconda3\lib\site-packages\wandb\__init__.py", line 304, in _init_headless
    "W&B process failed to launch, see: {}".format(path))
wandb.run_manager.LaunchError: W&B process failed to launch, see: wandb\debug.log

Process finished with exit code 1`

I guess the problem is in the wandb package version i run. 
Could you please write what versions exactly should i use? The requirements.txt file contains only package names without version numbers.
Thank you.

**Comment by borisdayma** [comment]
Hi, I think wandb has a temporary problem on Windows as they are updating the CLI.
Are you able to use Linux?

**Comment by convosasha** [comment]
Oh, I see. This explains why I wasn't able to run the simplest commands.
Im not able to use Linux at the moment so I'll have to find a different
solution.
Thank you any way!
Alex.

**Comment by borisdayma** [comment]
Try in a week, it should solve itself. Definitely worth using wandb if you do a lot of fine-tuning.
You can also use a docker container.

**Comment by convosasha** [comment]
Actually this is my first try of trainig a net. After working for years in
matlab, open source code is a pretty confusing thing :)
I tried to use your code for semantic segmentation since it looked
understandable to me and was trained on the same database that I used, so
I'll try it again later, as you suggested.
Thanks again.

**Comment by borisdayma** [comment]
Great, I think you're gonna have a lot of fun, with it. You're using the right tools!
I'm going to close this issue for now as I think it's not related to this repo but please reopen it in a week if you still have this problem.

**Comment by convosasha** [comment]
OK, thanks again!
